WIP: Fix/relatorio rescisao
kmee/kmee_odoo_addons pull request #23
Opened 2017-06-30 03:46 UTC by the-bmb

2017-07-03 20:21 UTC, mileo requested changes

2017-07-03 20:21 UTC, mileo commented on l10n_br_hr_payroll_report/models/hr_field_rescission.py
> +    codigo = fields.Integer(
Esta tabela não tem um campo name....

Opções:
- usar o atributo _rec_name
- ou implementar o método name_get
- ou trocar o campo descrição para name

2017-07-03 20:33 UTC, the-bmb commented
Depende do PR https://github.com/kmee/odoo-brazil-hr/pull/122/

2017-07-07 19:17 UTC, the-bmb commented
Necessário:
https://github.com/kmee/odoo-brazil-hr/pull/127

2017-07-10 22:28 UTC, wagnerpereirasp commented
:+1:

2017-07-10 22:28 UTC, merged